api:
  definitionClasses:
    - io.limberest.demo.api.Definition

request:
  fallbackContentType:
    get: application/json
  
tests:
  location: c:\eclipse_workspace\limberest-demo\test
  extensions:
    - .postman
    
json:
  prettyIndent: 2
  # orderedKeys: false
  # falseValuesOutput: true